# Generated by Django 4.2.2 on 2023-06-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isStaff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.OneToOneField(db_column='imagen_id', on_delete=django.db.models.deletion.RESTRICT, related_name='categoria', to='gestion.imagen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
